// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mcmcfn
Rcpp::List mcmcfn(arma::vec n, int P, int r, int Np, arma::mat datasets, int IndVar, int nbrsample, int burninsample, arma::vec CompoSelMean, arma::vec VarSelMean, arma::vec VarSelMeanGlobal, arma::vec priorcompsel, double probvarsel, int C, arma::mat EstMat1, arma::mat EstMat2, arma::field<arma::ivec> EstIMat1, int K, arma::field<arma::ivec> EstIMat2, arma::mat EstMat3, arma::field<arma::imat> Wtriplet_list, arma::field<arma::imat> Wbegfin_list, arma::vec beta, arma::mat interp_coef_mat, int chainNbr, bool streamline);
RcppExport SEXP _BayesClint_mcmcfn(SEXP nSEXP, SEXP PSEXP, SEXP rSEXP, SEXP NpSEXP, SEXP datasetsSEXP, SEXP IndVarSEXP, SEXP nbrsampleSEXP, SEXP burninsampleSEXP, SEXP CompoSelMeanSEXP, SEXP VarSelMeanSEXP, SEXP VarSelMeanGlobalSEXP, SEXP priorcompselSEXP, SEXP probvarselSEXP, SEXP CSEXP, SEXP EstMat1SEXP, SEXP EstMat2SEXP, SEXP EstIMat1SEXP, SEXP KSEXP, SEXP EstIMat2SEXP, SEXP EstMat3SEXP, SEXP Wtriplet_listSEXP, SEXP Wbegfin_listSEXP, SEXP betaSEXP, SEXP interp_coef_matSEXP, SEXP chainNbrSEXP, SEXP streamlineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type Np(NpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type IndVar(IndVarSEXP);
    Rcpp::traits::input_parameter< int >::type nbrsample(nbrsampleSEXP);
    Rcpp::traits::input_parameter< int >::type burninsample(burninsampleSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type CompoSelMean(CompoSelMeanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VarSelMean(VarSelMeanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VarSelMeanGlobal(VarSelMeanGlobalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type priorcompsel(priorcompselSEXP);
    Rcpp::traits::input_parameter< double >::type probvarsel(probvarselSEXP);
    Rcpp::traits::input_parameter< int >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type EstMat1(EstMat1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type EstMat2(EstMat2SEXP);
    Rcpp::traits::input_parameter< arma::field<arma::ivec> >::type EstIMat1(EstIMat1SEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::ivec> >::type EstIMat2(EstIMat2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type EstMat3(EstMat3SEXP);
    Rcpp::traits::input_parameter< arma::field<arma::imat> >::type Wtriplet_list(Wtriplet_listSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::imat> >::type Wbegfin_list(Wbegfin_listSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type interp_coef_mat(interp_coef_matSEXP);
    Rcpp::traits::input_parameter< int >::type chainNbr(chainNbrSEXP);
    Rcpp::traits::input_parameter< bool >::type streamline(streamlineSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcfn(n, P, r, Np, datasets, IndVar, nbrsample, burninsample, CompoSelMean, VarSelMean, VarSelMeanGlobal, priorcompsel, probvarsel, C, EstMat1, EstMat2, EstIMat1, K, EstIMat2, EstMat3, Wtriplet_list, Wbegfin_list, beta, interp_coef_mat, chainNbr, streamline));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesClint_mcmcfn", (DL_FUNC) &_BayesClint_mcmcfn, 26},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesClint(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
