# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcmcfn <- function(n, P, r, Np, datasets, IndVar, nbrsample, burninsample, CompoSelMean, VarSelMean, VarSelMeanGlobal, priorcompsel, probvarsel, C, EstMat1, EstMat2, EstIMat1, K, EstIMat2, EstMat3, Wtriplet_list, Wbegfin_list, beta, interp_coef_mat, chainNbr, streamline = TRUE) {
    .Call(`_BayesClint_mcmcfn`, n, P, r, Np, datasets, IndVar, nbrsample, burninsample, CompoSelMean, VarSelMean, VarSelMeanGlobal, priorcompsel, probvarsel, C, EstMat1, EstMat2, EstIMat1, K, EstIMat2, EstMat3, Wtriplet_list, Wbegfin_list, beta, interp_coef_mat, chainNbr, streamline)
}

